[pytest]
markers =
    Nearest_Neighbor_find_neighbor: "test find_neighbor method in the Nearest_Neighbor class"
    Nearest_Neighbor_predict: "test predict method in the Nearest_Neighbor class"
    Simple_Regression_Abs_train: "test train method in the Simple_Regression_Abs class"
    Simple_Regression_SE_train: "test train method in the Simple_Regression_SE class"
    Linear_Regression_SE_train: "test train method in the Linear_Regression_SE class"
    Linear_Regression_Ridge_train: "test train method in the Linear_Regression_Ridge class"
    Lasso_Regression_compute_gradient: "test compute_gradient method in the Lasso_Regression class"
    Lasso_Regression_update_w: "test update_w method in the Lasso_Regression class"
    Lasso_Regression_train: "test train method in the Lasso_Regression class"
